class PullError(Exception):
    pass

class PushError(Exception):
    pass

class ResourceExistsError(Exception):
    pass
